#!/usr/bin/env python2

"""
Copyright (c) 2006-2019 sqlmap developers (http://sqlmap.org/)
See the file 'LICENSE' for copying permission
"""

__product__ = "CloudFront (Amazon)"


def detect(resp):
    page = resp.text
    
    retval = all(_ in (page or "") for _ in ("Generated by cloudfront", "Request blocked"))
    
    return retval
