#!/usr/bin/env python2

"""
Copyright (c) 2006-2019 sqlmap developers (http://sqlmap.org/)
See the file 'LICENSE' for copying permission
"""

import re

from lib.module.wafCheck.config import HTTP_HEADER

__product__ = "ModSecurity: Open Source Web Application Firewall (Trustwave)"


def detect(resp):
    page = resp.text
    headers = resp.headers
    code = resp.status_code
    
    retval = re.search(r"Mod_Security|NOYB", headers.get(HTTP_HEADER.SERVER, ""), re.I) is not None
    retval |= re.search(r"(mod_security|Mod_Security|NOYB)", headers.get(HTTP_HEADER.SERVER, ""), re.I) is not None
    retval |= resp.reason == 'ModSecurity Action' and code == 403
    retval |= any(_ in (page or "") for _ in (
        "This error was generated by Mod_Security", "One or more things in your request were suspicious",
        "rules of the mod_security module", "Protected by Mod Security", "mod_security rules triggered",
        "/modsecurity-errorpage/", "ModSecurity IIS"))
    
    return retval
