#!/usr/bin/env python2

"""
Copyright (c) 2006-2019 sqlmap developers (http://sqlmap.org/)
See the file 'LICENSE' for copying permission
"""

__product__ = "Wordfence (Feedjit)"


def detect(resp):
    page = resp.text
    
    retval = any(_ in (page or "") for _ in (
        "A potentially unsafe operation has been detected in your request to this site",
        "Generated by Wordfence",
        "Your computer's time:",
        "Your access to this site has been limited",
        "This response was generated by Wordfence"))
    
    return retval
